name: NodeJ
title: Node.js API for the JVM
org: Project Odd
base_url: ''
github: http://github.com/projectodd/nodej

profiles:
  production:
    base_url: http://nodej.org
    deploy:
      host: github_pages
      branch: gh-pages

